title: CascadeAP
default_lang: en
author:
  name: 'Cascade Aerial Photography'
  email: contact@cascadeap.com
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
